### PR TITLE
Fix some comments

### PR DESCRIPTION
**Pull request by ZoeB**
Some simple comment fixes.  I've checked, and these are different to the pull requests at https://github.com/madler/zlib/pull/46/files and https://github.com/madler/zlib/pull/47/files .  Thanks!

### CODE REVIEW

**Comment by ZoeB** [comment]
Sorry, here are some more.

**Comment by vadmium** [comment]
Also in ChangeLog, under “Changes in 1.0.1”, it says “fix deflateParams() which could generated bad compressed data.” This should probably either be “could [have] generated”, or “could [generate] . . .”.

**Comment by ZoeB** [comment]
Done.  I'll set up another pull request accordingly...

**Comment by madler** [comment]
Fixed, thanks.

**Pull request closed without merging**
