### PR TITLE
Fixed vc14 projects, now it run ReleaseWithoutAsm fully OK

### PR DESCRIPTION
**Pull request by AfterWaLifu**
Also, static lib building debug/release without problems

### CODE REVIEW

**Comment by spaette** [comment]
FWIW, updated files for VS2017.

https://github.com/vaerksted/zlib

**Comment by spaette** [comment]
Hunt/Vollant

as contrib directory contents changed in 1.2.12

it might seem justifiable to add a vc17 directory


```
$ tar xf zlib-1.2.11.tar.gz
$ tar xf zlib-1.2.12.tar.gz
$ tree -d -L 1 zlib-1.2.11/contrib 
zlib-1.2.11/contrib
|-- ada
|-- amd64
|-- asm686
|-- blast
|-- delphi
|-- dotzlib
|-- gcc_gvmat64
|-- infback9
|-- inflate86
|-- iostream
|-- iostream2
|-- iostream3
|-- masmx64
|-- masmx86
|-- minizip
|-- pascal
|-- puff
|-- testzlib
|-- untgz
`-- vstudio

20 directories
$ tree -d -L 1 zlib-1.2.12/contrib
zlib-1.2.12/contrib
|-- ada
|-- blast
|-- delphi
|-- dotzlib
|-- gcc_gvmat64
|-- infback9
|-- iostream
|-- iostream2
|-- iostream3
|-- minizip
|-- pascal
|-- puff
|-- testzlib
|-- untgz
`-- vstudio

15 directories
$ 
```

**Comment by AraHaan** [comment]
I will be taking over this, vc14 is for vs2015, vc142 could be for vs2019, while I will do vc143 for vs2022.

**Comment by spaette** [comment]
`contrib/vstudio` files updated for Visual Studio 2022 would go in a `contrib/vstudio/vc17` directory

you opened a PR but therein provided no link to this current ticket

**Comment by AraHaan** [comment]
#732

**Comment by Neustradamus** [comment]
It will be nice to have all possibilities:
- v140 or vc140: Visual Studio 2015
- v141 or vc141: Visual Studio 2017
- v142 or vc142: Visual Studio 2019
- v143 or vc143: Visual Studio 2022

**Comment by spaette** [comment]
Purportedly, and this wasn't mentioned in your linked to PR, Visual Studio 2010 was the last version to support Itanium.

> why I did vc143

that's wrong

```
$ grep -r PlatformToolset zlib/contrib/vstudio/vc11/zlibvc.vcxproj | sed 1q
    <PlatformToolset>v110</PlatformToolset>
$ grep -r PlatformToolset zlib/contrib/vstudio/vc12/zlibvc.vcxproj | sed 1q
    <PlatformToolset>v120</PlatformToolset>
$ grep -r PlatformToolset zlib/contrib/vstudio/vc14/zlibvc.vcxproj | sed 1q
    <PlatformToolset>v140</PlatformToolset>
$ 
```

the `contrib/vstudio` subdirectories are named based on the *.sln files

```
$ sed -n 4p zlib/contrib/vstudio/vc12/zlibvc.sln
VisualStudioVersion = 12.0.40629.0
$ sed -n 4p zlib/contrib/vstudio/vc14/zlibvc.sln
VisualStudioVersion = 14.0.25420.1
$ 
```

**Comment by AraHaan** [comment]
A preview of what is also in my PR too: https://github.com/madler/zlib/pull/732#issuecomment-1292785054

**Comment by spaette** [comment]
1. An Issue should be opened requesting the addition of ARM and ARM64 support; if approved by the zlib developers an associated Pull Request could then be opened
2. An Issue should be opened requesting the addition of nuget content; if approved by the zlib developers an associated Pull Request could then be opened
3. A Pull Request should be opened exclusively updating contrib/vstudio files for Visual Studio 2022 to be located in a contrib/vstudio/vc17 directory, with the obligatory corresponding addition of an entry in contrib/vstudio/readme.txt

<hr>

> Purportedly, and this wasn't mentioned in your linked to PR, Visual Studio 2010 was the last version to support Itanium.

It is justifiable in 3. above to remove support for Itanium.

**Pull request closed without merging**
