### PR TITLE
minizip: remove a semicolon

### PR DESCRIPTION
**Pull request by likunyur**
Signed-off-by: Li kunyu <kunyu@nfschina.com>

### CODE REVIEW

**Comment by Neustradamus** [comment]
cc: @gvollant.

**Review by flomnes — APPROVED** [review]

**Comment by gvollant** [comment]
Of course I approve this syntax "no risk" cleanup

**Comment by gvollant** [comment]
@madler you can merge

**Review by tbeu — APPROVED** [review]

**Comment by madler** [comment]
Incorporated.

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/4572dfbe99b9fc6ea3aa1fa938e270bd45973cd0

**Pull request closed without merging**
