### PR TITLE
[RFC] Upstreaming fuzzers for oss-fuzz

### PR DESCRIPTION
**Pull request by bshastry**
Hello,

I created this pull request to gauge your attitude towards continuous fuzzing and upstream support for it. Presently all fuzzer harnesses are in the oss-fuzz repo (https://github.com/google/oss-fuzz/tree/master/projects/zlib) or inside the chromium codebase (https://cs.chromium.org/chromium/src/third_party/zlib/contrib/tests/fuzzers/)

CC @inferno-chromium @Dor1s (via https://github.com/google/oss-fuzz/issues/402#issuecomment-364628081)

Thank you
Bhargava

### CODE REVIEW

**Comment by Dor1s** [comment]
+1, it is highly recommended to store fuzz targets in the upstream repo and ideally use it for regression testing / in CI.

**Comment by bshastry** [comment]
Ping :-)

**Comment by bshastry** [comment]
@madler Would you be interested in this PR? :-)

**Comment by bshastry** [comment]
Closing PR since maintainer has not shown interest in over a year.

**Pull request closed without merging**
