### PR TITLE
Fix logic operator

### PR DESCRIPTION
**Pull request by tbeu**
Fix logic operator as reported by #384. FYI @mjunix @gvollant

### CODE REVIEW

**Comment by Neustradamus** [comment]
@gvollant: What do you think?

**Comment by gvollant** [comment]
I agree with this small fix

**Comment by AtariDreams** [comment]
Any update on this?

**Comment by gvollant** [comment]
@madler you can merge it for me

**Comment by madler** [comment]
Applied manually.

**Comment by madler** [comment]
Applied.

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/3061e5013c2569974fd7d830f2776b38da4e2691

**Pull request closed without merging**
