### PR TITLE
Updated CMakeLists.txt to minimum cmake 3.0.0

### PR DESCRIPTION
**Pull request by bmarques1995**
CMake is complaining of a very low cmake support version, so is recommended upgrade its version

### CODE REVIEW

**Comment by fredgan** [comment]
No other effects or modifications?

**Comment by bmarques1995** [comment]
> No other effects or modifications?

No, only this one

**Comment by fredgan** [comment]
So, the CMake versions are more widely covered, I don't understand what the complaint is.

**Comment by bmarques1995** [comment]
> So, the CMake versions are more widely covered, I don't understand what the complaint is.

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

**Comment by tbeu** [comment]
> Update the VERSION argument value or use a ... suffix to tell
> CMake that the project does not need compatibility with older versions.

Could set `cmake_minimum_required(VERSION 2.4.4...3.0.0)` alternatively.

**Comment by tbeu** [comment]
See also #774.

**Review by nmoinvaz — APPROVED** [review]

**Review by nmoinvaz — APPROVED** [review]

**Comment by vszakats** [comment]
CMake 3.27.0 released on 2023-07-18 warns if the minimum version is below 3.5:
```
CMake Deprecation Warning at CMakeLists.txt:39 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

Might make sense to bump to 3.5 to avoid this.

**Comment by bmarques1995** [comment]
Now the max is 3.15.0

**Comment by madler** [comment]
Applied.

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/9889e988689cd9fcc08e45010fff9548aae3dbff

**Pull request closed without merging**
