### PR TITLE
Add Cirrus CI; add --force_fail and --fail_fast options to example.c

### PR DESCRIPTION
**Pull request by dankegel**
I wanted to make this a pull request against https://github.com/ProgramMax/zlib/tree/develop
but Github won't let me, so here it is against madler's develop branch.
It's just Chris's branch plus --force_fail and --fail_fast options to example.c that I found useful,
as well as cirrus-ci builds on BSD, mac, linux, and windows.

The README now shows status badges for both Appveyor and Cirrus; see https://github.com/dankegel/zlib/tree/develop for what it looks like when the git repo has those two services enabled.

When cirrus-ci builds fail, Github displays test failures with links to source lines,
see example at https://github.com/dankegel/zlib/pull/3/checks?check_run_id=690339991
Perhaps more usefully, in pull requests they also show up in the 'Files changed' tab, see example at https://github.com/dankegel/zlib/pull/3/files (and scroll down to the 'Unchanged files with check annotations' section!).

(This pull request used to also add Linux builds via travis-ci.org and drone.io for Power, S390x, and Arm, but I've banished those to https://github.com/dankegel/zlib/commits/moreci for now.)

### CODE REVIEW

**Comment by ProgramMax** [comment]
If you want to merge the two pull requests, you can save your changes off to the side and delete your fork of madler/zlib. Then fork my zlib, fetch it, reapply your changes, upload, and submit a pull request to my fork. Once included in my fork it becomes included in my pull request.

**Comment by ProgramMax** [comment]
You'll probably want to add badges to the README.md to indicate which builds are passing / failing.

**Comment by dankegel** [comment]
OK, badge added.  (Annoyingly, looks like Chrome caches badges aggressively.)

I hesitate to delete my repo... that's given me trouble in the past.  Could you consider the following commands instead?
```
git remote add dank https://github.com/dankegel/zlib
git fetch dank
git checkout -b dank-develop dank/develop
git checkout develop
git merge --ff-only dank-develop
```
?

**Comment by dankegel** [comment]
Or you could just land yours and I could rebase this one afterwards.

**Comment by ProgramMax** [comment]
That option works for me. :)

**Comment by mscastanho** [comment]
@dankegel, there is a simpler way to do this. You can just add @ProgramMax's fork as a remote on your local zlib repo:

    git remote add gh-programmax https://github.com/ProgramMax/zlib.git

Create a branch based on the branch he used to open his PR (`develop`):

    git fetch gh-programmax develop:ci-integration 

(here the local branch will be called `ci-integration`)
add your changes to this branch, then push it to your own GitHub fork:

    git push origin ci-integration

(assuming you have your own zlib fork on GitHub as the `origin` git remote)

And then open a PR from your `ci-integration` (or other name you used) to @ProgramMax 's `develop` branch on his fork. Once he merges the changes there, GitHub will automatically update PR #492 with your changes.

**Comment by dankegel** [comment]
Well, yes, that is what I tried to do.  I rebase onto his branch whenever he updates it.
But when when I try to create a PR from my branch to @ProgramMax's develop branch, github does not give me the option; his branch is missing from the list of allowed targets; here's what I see: http://kegel.com/github-hates-me.png

Evidently this is a known issue with github:
http://srcmvn.com/blog/2013/03/14/sending-a-pull-request-on-github-even-when-the-base-repository-you-want-is-missing

The suggested workaround is to construct a URL like https://github.com/DanKegel/zlib/pull/new/ProgramMax:develop...DanKegel:develop
and sure enough, that worked!  See https://github.com/ProgramMax/zlib/pull/2

Closing in favor of https://github.com/ProgramMax/zlib/pull/2 for now.

**Pull request closed without merging**
