### PR TITLE
Add iOS headless building

### PR DESCRIPTION
**Pull request by slingthor**
Signed-off-by: Ingthor Hjalmarsson ihjalmarsson@apple.com

### CODE REVIEW

**Comment by Neustradamus** [comment]
@slingthor: Nice :)

**Comment by tbeu** [comment]
I miss the motivation why examples are permanently disabled on iOS.

Duplicate of https://github.com/madler/zlib/pull/224, https://github.com/madler/zlib/pull/283, https://github.com/madler/zlib/pull/487, https://github.com/madler/zlib/pull/824, https://github.com/madler/zlib/pull/861, #870.

**Comment by madler** [comment]
I applied a different request to provide an option to not build the examples (default is to build them). You can resubmit a request to turn off building the examples in the case of iOS, with the rationale for that. Thanks.

**Comment by Neustradamus** [comment]
@slingthor: Can you try the current devel branch?
What are your results?

Thanks in advance.

**Pull request closed without merging**
