### PR TITLE
build with vs2015

### PR DESCRIPTION
**Pull request by zbrad**
Updated to build with VS2015.   Two separate builds:

contrib\vc14\lib\zlibstatic.sln
contrib\vc14\dll\zlibdll.sln

### CODE REVIEW

**Comment by mlt** [comment]
One can generate any VS version solution with CMake

**Comment by madler** [comment]
There are many Visual Studio pull requests. Can someone who is able to test them across versions of Visual Studio merge them into a single pull request? Also please test it with the latest zlib develop branch here on github, and account for functions that have been added since 1.2.8. Thank you.

**Comment by AraHaan** [comment]
See #182 which is based from #167. Other than that it also Provides some other fixes to the definition file and the resource script for the version info resource. The export Definition file was also fixed in it for all of the Project files and includes VS2013 for those who still use it. It targets the latest Develop branch though.

**Comment by madler** [comment]
Please see zlib 1.2.9 for updated vstudio support. Please create new issues or new pull requests if there are problems or desired behaviors against that version. Thanks.

**Comment by zbrad** [comment]
let me see if I can spend some cycles on this later this week

**Comment by AraHaan** [comment]
Note: Visual Studio 2017 is not provided since I don't have enough hard disk space to install it. So sorry if I can only provide up to VS2015.

**Pull request closed without merging**
