### PR TITLE
Fix typos found by codespell in minizip

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
@gvollant Would you agree to fixing these typo in `zlib/contrib/minizip`?

**Comment by DimitriPapadopoulos** [comment]
If merged, additional effort would be needed to improve English.

**Comment by Neustradamus** [comment]
@gvollant: Can you look?

**Review by tbeu — APPROVED** [review]

**Comment by gvollant** [comment]
@madler @Neustradamus @DimitriPapadopoulos thank you for the fixes, can be merged for me

**Comment by madler** [comment]
Applied.

**Comment by spaette** [comment]
As this was merged https://github.com/madler/zlib/pull/592 can be closed.

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/379bbda363d1925bdaf50195e74052ead801490c

**Pull request merged**
