### PR TITLE
Fix building outside source tree.

### PR DESCRIPTION
**Pull request by mtl1979**
Fix configure and Makefile.in to work when zlib is built outside of directory containing sources.

Fixes madler/zlib#60 and madler/zlib#81

### CODE REVIEW

**Comment by wipkirill** [comment]
Hi, I have applied this patch and have the following issue while building:

gcc -O3  -DHAVE_HIDDEN -I. -I/Users/kirill/github/zlib -c -o example.o /Users/kirill/github/zlib/test/example.c
gcc -O3  -DHAVE_HIDDEN -c -o adler32.o /Users/kirill/github/zlib/adler32.c
In file included from /Users/kirill/github/zlib/zutil.h:22:0,
                 from /Users/kirill/github/zlib/adler32.c:8:
/Users/kirill/github/zlib/zlib.h:86:5: error: unknown type name 'z_const'
     z_const Bytef *next_in;     /* next input byte */
     ^
/Users/kirill/github/zlib/zlib.h:86:19: error: expected ':', ',', ';', '}' or '__attribute__' before '*' token
     z_const Bytef *next_in;     /* next input byte */
                   ^
In file included from /Users/kirill/github/zlib/zlib.h:34:0,
                 from /Users/kirill/github/zlib/zutil.h:22,
                 from /Users/kirill/github/zlib/adler32.c:8:
/Users/kirill/github/zlib/zlib.h:1026:33: error: unknown type name 'z_const'
                                 z_const unsigned char FAR * FAR *));
                                 ^
/Users/kirill/github/zlib/zlib.h:1030:37: error: unknown type name 'in_func'
                                     in_func in, void FAR *in_desc,
                                     ^
In file included from /Users/kirill/github/zlib/zutil.h:22:0,
                 from /Users/kirill/github/zlib/adler32.c:8:
/Users/kirill/github/zlib/zlib.h:1349:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Z_ARG'
 ZEXTERN int ZEXPORTVA gzprintf Z_ARG((gzFile file, const char *format, ...));
                                ^
/Users/kirill/github/zlib/zlib.h:1748:15: error: unknown type name 'z_crc_t'
 ZEXTERN const z_crc_t FAR * ZEXPORT get_crc_table    OF((void));
               ^
/Users/kirill/github/zlib/zlib.h:1758:44: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Z_ARG'
 ZEXTERN int            ZEXPORTVA gzvprintf Z_ARG((gzFile file,
                                            ^
In file included from /Users/kirill/github/zlib/adler32.c:8:0:
/Users/kirill/github/zlib/zutil.h:47:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'char'
 extern z_const char * const z_errmsg[10]; /* indexed by 2-zlib_error */
                ^
/Users/kirill/github/zlib/adler32.c: In function 'adler32_combine64':
/Users/kirill/github/zlib/adler32.c:176:15: error: argument 'len2' doesn't match prototype
     z_off64_t len2;
               ^
In file included from /Users/kirill/github/zlib/adler32.c:8:0:
/Users/kirill/github/zlib/zutil.h:173:27: error: prototype declaration
     ZEXTERN uLong ZEXPORT adler32_combine64 OF((uLong, uLong, z_off_t));
                           ^
make: *** [adler32.o] Error 1

Everything works fine if I do configure inside the source tree

**Comment by mtl1979** [comment]
That sure looks like corrupt zconf.h.in or zconf.h... I tried compiling here and it works after adding the missing -I. to the %.o and %.lo targets in Makefile.in ... Gonna amend the patch with that fix...

**Comment by wipkirill** [comment]
Surprisingly I found a workaround which also worked out at configure script:
# copy clean zconf.h for subsequent edits
cp -p $SRCDIR/zconf.h.in zconf.h

# We need to delete zconf.h from source directory if building outside of it
#if [ "$SRCDIR" != "$BUILDDIR" ]; then rm -f $SRCDIR/zconf.h; fi 

Not sure if it is a right solution in this case.

**Comment by mtl1979** [comment]
@wipkirill The original problem was that it didn't find the generated zconf.h, so it defaulted to the bundled zconf.h ... With some compilers the default settings actually worked, but some compilers didn't even look for the bundled zconf.h and actually bailed out without even trying to compile. Working with differences in compilers and different versions is sometimes hard... I backported the fix from zlib-ng project before gcc 4.9 was the default version and gcc 4.9 changes quite a lot compared to gcc 4.8. I learnt it the hard way...

**Comment by wipkirill** [comment]
Ok, I won't repeat it at home and wait for your patch, tnx :)

**Comment by mtl1979** [comment]
@wipkirill Commit d8383fa8981d90cc158c4d202173e15a12e704a4 should have the patch included...

**Comment by madler** [comment]
Done on develop branch. See https://github.com/madler/zlib/commit/55d98b4c302c74b619968bd02cf3b5e18d845977

**Comment by Neustradamus** [comment]
@mtl1979, @wipkirill: Z_ARG has been removed:
- https://github.com/madler/zlib/commit/3f635df97edbb85f55f8e991e5f00d94f4132a14

**Comment by mtl1979** [comment]
> @mtl1979, @wipkirill: Z_ARG has been removed:
> 
> * [3f635df](https://github.com/madler/zlib/commit/3f635df97edbb85f55f8e991e5f00d94f4132a14)

The original issue wasn't about `Z_ARG`.

**Pull request closed without merging**
