### PR TITLE
Fix the problem of using static library linking

### PR DESCRIPTION
**Pull request by xengine-qyt**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@madler: What do you think?

**Comment by xengine-qyt** [comment]
Cross-compiling to static libraries on Android platforms requires this option for linking and compiling.

**Comment by Neustradamus** [comment]
@madler: Can you look this PR?

**Comment by xengine-qyt** [comment]
fixed this:https://github.com/madler/zlib/issues/882

**Comment by madler** [comment]
Thanks. Applied, though avoiding double `-fPIC`'s.

**Comment by raphaelts3** [comment]
This actually resolved an issue I was having for days, it was very similar to the one referenced on #882:
```lib/libz.a(zutil.o): relocation R_X86_64_PC32 against symbol `z_errmsg' can not be used when making a shared object; recompile with -fPIC```

I don't know much about the double `-fPIC` but it surely did some trick.

PS: I've tried configure with CHOST, `--static`, tried to build with cmake and a bunch of other things, but this was the actual solution.

PSS: Sorry for commenting in a closed PR, but this was such a relief to find, that I felt that was going to be worth sharing my experience.

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/4f8a17e8cbf5856d8a27e112ed41a110f54129dd

**Pull request closed without merging**
