### PR TITLE
Added VS2013 and VS2015 project files.

### PR DESCRIPTION
**Pull request by AraHaan**
On top of the Project Files, I fixed the issue with compile on the
Definition files, and the resource files on generating wrong version
information.

Originally from #167 but since that Pull request cant be updated due to it was deleted by a friend from back when it was in their org I had to make a new Pull request for my changes today.

This also changes some ``Uncompress`` words in the readme text file for the visual studio projects to ``Decompress`` as it fits more.

### CODE REVIEW

**Comment by madler** [comment]
Thank you for your work on this!

There are new functions for 1.2.9 that could be added to the .def file. I don't fully understand why the functions need to be numbered, but if they do, then here are the new functions:

```
inflateCodesUsed()
uncompress2()
gzfread()
gzfwrite()
deflateGetDictionary()
```

**Comment by AraHaan** [comment]
hmm, maybe the compiler likes ordinals on them to know the order of implementation or maybe it markes the actual order to be exported. Other than that idk myself.

**Comment by madler** [comment]
Incorporated. Thanks!

**Comment by AraHaan** [comment]
yw

**Pull request closed without merging**
