### PR TITLE
cmake: respect custom RC flags with mingw

### PR DESCRIPTION
**Pull request by vszakats**
Before this patch, `zlib.rc` was compiled using a manual command [1] when
using the MinGW toolchain. This method ignores `CMAKE_RC_FLAGS` and
offers no other way to pass a custom flag, breaking the build in cases
where a custom windres option is required. E.g. `--target=` or `-I` on
some platforms and configuration, in particular with llvm-windres.

This patch deletes the special case for MinGW and lets CMake compile the
`.rc` file via the standard way used for all `WIN32`.

Also:

- Adjust the condition for dealing with the `.rc` file from `NOT MINGW`
  to `WIN32`, thus omitting this unnecessary input file for non-Windows
  platforms.

- Delete the MinGW-specific RC flag `GCC_WINDRES`.
  `GCC_WINDRES` was protecting logic that compiles fine with recent
  `windres` versions. Also, the protected line contained obsolete,
  16-bit era keywords that had no effect for a long time. [2]

- Delete the MinGW-specific defaulting logic for `CMAKE_RC_COMPILER`.
  This is done by CMake automatically, to the more portable default
  value `windres` (there is no `.exe` extension in cross-toolchains).

[1] dc5a43ebfadb6b775f6e64bfeb5a461c66acb394
[2] https://docs.microsoft.com/windows/win32/menurc/common-resource-attributes

---

This fixes build errors like this one:
```
$ cmake . -B bld -Wno-dev -DCMAKE_SYSTEM_NAME=Windows \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_MESSAGE=NEVER \
  -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SYSROOT=/usr/local/opt/mingw-w64/toolchain-x86_64 \
  -DCMAKE_C_COMPILER_TARGET=x86_64-w64-mingw32 -DCMAKE_C_COMPILER=clang \
  -DCMAKE_AR=/usr/local/opt/llvm/bin/llvm-ar \
  '-DCMAKE_RC_FLAGS=--target=pe-x86-64 -I/usr/local/opt/mingw-w64/toolchain-x86_64/x86_64-w64-mingw32/include' \
  '-DCMAKE_C_FLAGS=-Wno-unused-command-line-argument -Wno-deprecated-non-prototype -fuse-ld=lld -Wl,-s -static-libgcc'
-- The C compiler identification is Clang 15.0.3
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Renaming
--     /sandbox/zlib/zconf.h
-- to 'zconf.h.included' because this file is included with zlib
-- but CMake generates it automatically in the build directory.
-- Configuring done
-- Generating done
-- Build files have been written to: /sandbox/zlib/bld
++ pwd
+ make --directory=bld --jobs=1 install DESTDIR=/sandbox/zlib/x64-msvcrt VERBOSE=1
/usr/local/Cellar/cmake/3.24.2/bin/cmake -S/sandbox/zlib -B/sandbox/zlib/bld --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.24.2/bin/cmake -E cmake_progress_start /sandbox/zlib/bld/CMakeFiles /sandbox/zlib/bld//CMakeFiles/progress.marks
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 all
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/zlib.dir/build.make CMakeFiles/zlib.dir/depend
[  2%] Generating zlib1rc.obj
/usr/local/opt/llvm/bin/llvm-windres -D GCC_WINDRES -I /sandbox/zlib -I /sandbox/zlib/bld -o /sandbox/zlib/bld/zlib1rc.obj -i /sandbox/zlib/win32/zlib1.rc
/sandbox/zlib/win32/zlib1.rc:1:10: fatal error: 'winver.h' file not found
#include <winver.h>
         ^~~~~~~~~~
1 error generated.
llvm-rc: Preprocessing failed.
make[2]: *** [zlib1rc.obj] Error 1
make[1]: *** [CMakeFiles/zlib.dir/all] Error 2
make: *** [all] Error 2
```

### CODE REVIEW

**Comment by vszakats** [comment]
@madler Any love for this PR?

**Comment by vszakats** [comment]
@nmoinvaz Can you enable CI workflows for this PR please?

**Comment by nmoinvaz** [comment]
Hey @vszakats, sorry I don't have access. I'm just a pleb like everybody else here. 😂

**Comment by vszakats** [comment]
Oh, okay, no worries, I do understand the feeling! :)

[ as a shot in the abyss why this PR is not going anywhere, I was about to reinstate the Windows 16-bit bits, if maybe this is a reason for the silence. For the sake of all those Windows 3.11 users out there. One can only guess. ]

**Comment by vszakats** [comment]
Updated the patch to keep support for these legacy bits:
1. Windows 16-bit Resource flags.
2. MinGW releases that do not support those Windows 16-bit Resource flags.

**Comment by vszakats** [comment]
Added a build error log to the top post.

**Comment by vszakats** [comment]
Any interest in merging this? Or concerns to address that would allow merging?

**Comment by vszakats** [comment]
If using 1K more of RAM in Windows 16-bit is fine with `zlib.dll`, the second and third commits can be deleted.

**Comment by vszakats** [comment]
Deleted the Windows 16-bit legacy resource flags once again.

**Comment by Neustradamus** [comment]
@vszakats: Why have you closed this PR?

**Comment by vszakats** [comment]
Seeing this pending for a year+ (through 2 releases, and without zero feedback, not even allowing tests to run) and seeing other fixes (for even worse bugs) with 5+ years of wait, it appears that zlib is uninterested to touch CMake or even give any feedback to know what it wants.

I think this patch is solid and the workarounds for this bug are painful, so if someone is willing to deal with the "process" at zlib, or zlib wants to cherry pick it manually, it would improve things for everyone and feel free to do it.

**Pull request closed without merging**
