### PR TITLE
Fix version of MiniUnz

### PR DESCRIPTION
**Pull request by tbeu**
Match the version as given in the miniunz.c header comment. @gvollant

### CODE REVIEW

**Comment by tbeu** [comment]
Since this is in the contrib stuff: I tried to contact Gilles Vollant few years ago, but got no replies.

**Comment by Neustradamus** [comment]
@gvollant: What do you think?

**Comment by gvollant** [comment]
I agree

**Comment by madler** [comment]
Applied.

**Comment by tbeu** [comment]
> Applied.

Cannot find it. Is it already pushed?

**Comment by Neustradamus** [comment]
@tbeu: Good catch, it has not been applied.

**Pull request closed without merging**
