### PR TITLE
Security and warning fix for minizip

### PR DESCRIPTION
**Pull request by gvollant**
apply fix suggested at https://github.com/madler/zlib/issues/693 #693
remove unused code and not useful test for free

### CODE REVIEW

**Comment by Neustradamus** [comment]
@gvollant: Can you update (c) and version too?
- https://github.com/madler/zlib/tree/master/contrib/minizip

**Comment by tbeu** [comment]
Should this PR be targeted for development branch instead of master?

**Comment by madler** [comment]
Applied.

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/138c93cffb76f5c24e4ae6e81e6210428856f825

**Pull request closed without merging**
