### PR TITLE
Added VS2013 and VS2015 Project files.

### LINKED ISSUE #166: make vc14 (Visual Studio 2015) Project files.
Would be very simple if there was project files for vc14, I use the latest supplied in VS2015.

### PR DESCRIPTION
**Pull request by AraHaan**
Also Modified tthe Readme file on this to say that I added in VS2013 and
VS2015 projects to. Should close #166.

### CODE REVIEW

**Comment by madler** [comment]
There are many Visual Studio pull requests. Can someone who is able to test them across versions of Visual Studio merge them into a single pull request? Also please test it with the latest zlib develop branch here on github, and account for functions that have been added since 1.2.8. Thank you.

**Comment by AraHaan** [comment]
ok.

**Comment by AraHaan** [comment]
Well it should work on the projects I created sadly since a long time ago I sadly have to remake this PR anyway because of the sad fact that a friend of mine deleted the fork after I made this PR when it was forked to their org so yeah.

**Comment by AraHaan** [comment]
ok, the only issue I see for VIsual Styudio 2015 and 2013 on Develop branch is in zconf.h:

it is a problem with ``ssize_t`` it is not in sys/types.h`` nor in ``stddef.h``. I hear it is defined in ``BaseTsd.h`` as ``SSIZE_T`` So adding this right before the ``typedef ssize_t z_ssize_t;`` Will fix it.

```c
#    if defined(_MSC_VER)
#    include <BaseTsd.h>
         typedef SSIZE_T ssize_t;
#    endif
```

**Comment by AraHaan** [comment]
I noticed an issue with the Resource scripts to so I corrected them with the right way to show the version for windows.

Note for correct display Windows considers all ``.``'s in the fields in these 2 and ignores everything after the fist ``.`` in order for that to not get discarded separate each number in the versions with a ``, ``

So basically the resource script after my fix:

```rc
#include <windows.h>

#define IDR_VERSION1  1
IDR_VERSION1	VERSIONINFO	MOVEABLE IMPURE LOADONCALL DISCARDABLE
  FILEVERSION	 1, 2, 8, 1
  PRODUCTVERSION 1, 2, 8, 1
  FILEFLAGSMASK	VS_FFI_FILEFLAGSMASK
  FILEFLAGS	0
  FILEOS	VOS_DOS_WINDOWS32
  FILETYPE	VFT_DLL
  FILESUBTYPE	0	// not used
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904E4"
    //language ID = U.S. English, char set = Windows, Multilingual

    BEGIN
      VALUE "FileDescription", "zlib data compression and ZIP file I/O library\0"
      VALUE "FileVersion",	"1.2.8.1\0"
      VALUE "InternalName",	"zlib\0"
      VALUE "OriginalFilename",	"zlibwapi.dll\0"
      VALUE "ProductName",	"ZLib.DLL\0"
      VALUE "Comments","DLL support by Alessandro Iacopetti & Gilles Vollant\0"
      VALUE "LegalCopyright", "(C) 1995-2013 Jean-loup Gailly & Mark Adler\0"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x0409, 1252
  END
END
```

**Comment by madler** [comment]
Let me know if this addresses the ssize_t problem:

```
diff --git a/zconf.h.in b/zconf.h.in
index aee94b0..b131ce9 100644
--- a/zconf.h.in
+++ b/zconf.h.in
@@ -240,8 +240,13 @@
 #  ifdef NO_SSIZE_T
      typedef NO_SSIZE_T z_ssize_t;
 #  else
+#    include <stddef.h>
 #    include <sys/types.h>
-     typedef ssize_t z_ssize_t;
+#    ifdef MSC_VER
+       typedef intptr_t z_ssize_t;
+#    else
+       typedef ssize_t z_ssize_t;
+#    endif
 #  endif
 #  undef z_longlong
 #endif

```

**Comment by AraHaan** [comment]
yep it fixes the ssize_t issue exactly.

**Comment by madler** [comment]
Thanks. Try the latest develop branch. Some warnings should go away as well.

**Comment by AraHaan** [comment]
Ok, Recloning it on my computer as I could not for some reason update the develop branch from your develop branch it wanted to update from master.

**Comment by madler** [comment]
You can just download a .zip file: https://github.com/madler/zlib/archive/develop.zip

**Comment by AraHaan** [comment]
I could, but I like to clone because it's easier to track changes with the diff stuff.

**Comment by AraHaan** [comment]
Ok, time to close this one for #182.

**Pull request closed without merging**
