### PR TITLE
Fix typos found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by spaette** [comment]
`https://github.com/madler/zlib/pull/673#issuecomment-1224913167`

**Comment by DimitriPapadopoulos** [comment]
I thought so, that's why I have two commits – one outside `config` and one inside `config`. Do you want me to discard the one inside `config`? But then these are just typo fixes.

**Comment by DimitriPapadopoulos** [comment]
@spaette Fixed, see also #782, #783, #784.

**Comment by spaette** [comment]
it's unknown whether approved changes would be implemented in a local branch or directly into the master branch

<hr>

@anisimkov is unlikely to respond to your ping

the relevant Issue which had a linked to comment above had these lines

```
sed -i "s/Attension/Attention/g" zlib/contrib/ada/readme.txt
sed -i "s/Comression/Compression/g" zlib/contrib/ada/zlib-streams.ads
sed -i "s/stategy/strategy/g" zlib/contrib/ada/zlib.ads
```

and also these

```
sed -i "s/compearing/comparing/g" zlib/contrib/ada/test.adb
sed -i "s/incompartible/incompatible/g" zlib/contrib/ada/readme.txt
sed -i "s/spetsified/specified/g" zlib/contrib/ada/test.adb
```

you further suggest a change as follows

```diff
        --  We allow ZLib to make header only in case of default header type.
-       --  Otherwise we would either do header by ourselfs, or do not do
+       --  Otherwise we would either do header by ourselves, or do not do
        --  header at all.
```

<hr>

@hravnx approved these changes to dotzlib

```
sed -i "s/implmeneted/implemented/g" zlib/contrib/dotzlib/DotZLib/ChecksumImpl.cs
sed -i "s/suppported/supported/g" zlib/contrib/dotzlib/DotZLib/GZipStream.cs
```

the relevant Issue which had a linked to comment above also has these lines 

```
sed -i "s/dereived/derived/g" zlib/contrib/dotzlib/DotZLib/CodecBase.cs
sed -i "s/esclude/exclude/g" zlib/contrib/dotzlib/readme.txt
sed -i "s/proccesing/processing/g" zlib/contrib/dotzlib/DotZLib/CodecBase.cs
```

<hr>

@gvollant last year had submitted pulls to this repo

the relevant Issue which had a linked to comment above had these lines

```
# sed -i "s/derrived/derived/g" zlib/contrib/minizip/MiniZip64_Changes.txt
sed -i "s/choosen/chosen/g" zlib/contrib/minizip/ioapi.h
sed -i "s/comparision/comparison/g" zlib/contrib/minizip/unzip.h
sed -i "s/currenty/currently/g" zlib/contrib/minizip/zip.c
sed -i "s/defaut/default/g" zlib/contrib/minizip/unzip.c
sed -i "s/defaut/default/g" zlib/contrib/minizip/unzip.h
sed -i "s/depedent/dependent/g" zlib/contrib/minizip/zip.c
sed -i "s/easilty/easily/g" zlib/contrib/minizip/unzip.c
sed -i "s/extened/extended/g" zlib/contrib/minizip/zip.c
sed -i "s/follwed/followed/g" zlib/contrib/puff/puff.c
sed -i "s/recreting/recreating/g" zlib/contrib/minizip/zip.c
sed -i "s/somes/some/g" zlib/contrib/minizip/unzip.h
sed -i "s/structore/structure/g" zlib/contrib/minizip/unzip.c
sed -i "s/structore/structure/g" zlib/contrib/minizip/zip.c
```

the pull includes some additional exposed typos

**Comment by spaette** [comment]
before pursuing any more work on the now ada and minizip separate pulls my suggestion would be to first receive confirmation that the relevant contributors want to spend the time to review updates to their own contributions in terms of typo fixes

as pertains to ada that response is unlikely  to arrive

**Comment by DimitriPapadopoulos** [comment]
If the initial contributors do not want to spend the time to maintain their code, will it remain as it is forever? What is the rationale behind this decision? It seems at odds with the whole point of open source.

**Comment by DimitriPapadopoulos** [comment]
In any case, I understand ada and minizip are not a priority.

I haven't found yet the "relevant PR" you refer to, but I have added the missing typos to the codespell dictionary of typos: https://github.com/codespell-project/codespell/pull/2742

What about changes to zlib itself (this merge request)?

**Comment by DimitriPapadopoulos** [comment]
> it's unknown whether approved changes would be implemented in a local branch or directly into the master branch

But then how to create pull requests? Pull requests are usually created against the main/master branch. How to create pull requests?

**Comment by spaette** [comment]
Sometimes there are intentions to schedule changes concomitant with an upcoming new release.

Occasionally code or bundled code as it were may become described as abandonware or orphanware.

> this merge request

I'm neither designated as a Reviewer nor have I write authority for this repo.

<hr>

AFAIK, pertaining to contrib subdirectories it is not a matter of priorities.

the relevant <s>Issue</s> PR which had a linked to comment above

https://github.com/madler/zlib/pull/775#issuecomment-1433730693

> it's unknown whether approved changes would
> be implemented in a local branch or directly into
> the master branch

The master branch in this repo is the correct location for opening Issues and PRs.

Maintainers have their own individual or collective approch to changes in the source code.

**Comment by DimitriPapadopoulos** [comment]
I see, nothing's certain.

**Comment by spaette** [comment]
many typos fixes proposed on 7-5-2022 were incorporated on 8-23-2022

**Comment by spaette** [comment]
_cf_: `#784` (Open)

contrib/minizip/unzip.c
contrib/minizip/unzip.h

this isn't a request but as long at you've submitted a minizip bulk typo fix see also my comment on `#592`

noting @sredna in that same PR submitted a layout change for a code comment contrib/minizip/unzip.c

**Comment by gvollant** [comment]
are somes change linked with #784 ?

**Comment by DimitriPapadopoulos** [comment]
@gvollant It had been suggested I open different merge requests for some subdirectories maintained by their respective contributors
* #782 fixes typos in **`contrib/ada`**, but I have closed it for lack of response
* #783 fixes typos in **`contrib/dotzlib`**, it has been approved but never merged,
* #784 fixes typos in  **`contrib/minizip`**.

This merge request #775 fixes typos outside these subdirectories.

**Comment by spaette** [comment]
> This merge request `#775` fixes typos outside these subdirectories.

specifically the typos
endianness, formerly, latest, recompression, update

respectively in
crc32.c, README, FAQ, examples/fitblk.c, and configure

**Comment by madler** [comment]
Applied.

**Comment by spaette** [comment]
_cf_: `#782`

@anisimkov had not responded to the comment of @DimitriPapadopoulos

looks like the content of all of the pulls of @DimitriPapadopoulos have been committed to the develop branch

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/c7ddcc2e0e8bb397ad720564228b538135ec11d8

**Pull request closed without merging**
