### PR TITLE
minizip, add support for Haiku

### PR DESCRIPTION
**Pull request by Begasus**
Patch isn't mine, it was done in 2017 by @extrowork, seems fine to see if this could get up streamed?

https://github.com/haikuports/haikuports/blob/14c2cab5428145b93232cb69683a67bbe68a9f06/app-arch/minizip/patches/minizip-1.2.11.patchset

### CODE REVIEW

**Comment by Begasus** [comment]
Came across this when updating zlib/minizip at haikuports: https://github.com/haikuports/haikuports/pull/7394

**Comment by Neustradamus** [comment]
@madler: Have you seen this PR?

**Comment by Neustradamus** [comment]
@gvollant: Can you look?

**Comment by gvollant** [comment]
I added PR #830

**Comment by Begasus** [comment]
Thanks, this one can be closed then I guess :)

**Comment by Neustradamus** [comment]
Zlib PR 830 from @gvollant Minizip author:
- https://github.com/madler/zlib/pull/830

"Support Haiku in minizip." merged commit in upstream Zlib develop branch:
- https://github.com/madler/zlib/commit/aa154e3da0d98629bbefe79cdfba8bc7178dc4ad

There is a little change.

Original HaikuPorts PR from Zoltán Mizsei @extrowerk (merged by @diversys) on GitHub:
- https://github.com/haikuports/haikuports/pull/1593

Zlib and Minizip HaikuPorts files:
- https://github.com/haikuports/haikuports/commits/master/app-arch/minizip
- https://github.com/haikuports/haikuports/commits/master/sys-libs/zlib/patches

Updated HaikuPorts PR from @Begasus:
- https://github.com/haikuports/haikuports/pull/7394

Requested PR in Zlib upstream from @Begasus:
- https://github.com/madler/zlib/pull/741

cc: @madler, @waddlesplash, @korli, @pulkomandy, @fbrosson.

**Pull request closed without merging**
