### PR TITLE
Added VC12 VC14 compatible project, UI, native MASM targets

### PR DESCRIPTION
**Pull request by ENikS**
http://www.codeproject.com/Articles/888836/consuming-zlib-in-boost-using-Visual-Studio-MSBuil

### CODE REVIEW

**Comment by rhuijben** [comment]
There are already multiple similar pull requests/issues. Note that the contributed MASM files have known issues that in some cases produce invalid result while decompressing data, so I would recommend *not using* these until these bugs are fixed.

**Comment by rhuijben** [comment]
See issue 41

**Comment by rhuijben** [comment]
See issue#41

**Comment by ENikS** [comment]
Although it is similar to other pull requests it has unique improvements: It has specialized General Property page specifically modified for zlib so only valid options could be set (You can't set build to EXE type for example). It uses MASM targets instead of custom build shell. It integrates much better during build, error reporting and such.
As for using or not using ASM modules it is up to the developer. If you just disable it how are we suppose to fix them? 
Implementation could be selected on the UI property page, just another configuration parameter. It also could be set to use C++ implementation by default.

**Comment by rhuijben** [comment]
Perhaps somebody should look at the files to fix them. They were created by taking the compiler output of a very old version of the code and then hand optimizing some constructs. Several bugs were fixed in the original code since then, but nobody cared to fix up the same problems in the assembly. Then some variables slightly changed behavior and the assembly wasn't modified. The project itself calls them a contribution, so doesn't spend time on fixing these old files. (Waiting for somebody to contribute fixes). If you really want to spend days tracking down impossible bug requests, do enable the assembly optimizations. (I've done that for the Subversion project after we got such reports). Don't tell me you haven't been warned.

Most likely the compilers have been improved in the last 15 years (the optimizations are based on VC 6.0/1998 output), so it is doubtful if these old optimizations make any sense today at all, because modern compilers optimize for modern CPUs, not those that are not being sold for 15 years or so. I couldn't measure a slowdown after disabling the optimizations. I did see a huge drop in network data errors reported by our users.

**Comment by ENikS** [comment]
I see your point. I could make C++ default and disable ASM switch in UI or I could remove ASM modules all together. If you could verify that impact on performance is insignificant and it is not worth fixing I'll remove these.

**Comment by madler** [comment]
There are many Visual Studio pull requests. Can someone who is able to test them across versions of Visual Studio merge them into a single pull request? Also please test it with the latest zlib develop branch here on github, and account for functions that have been added since 1.2.8. Thank you.

**Comment by AraHaan** [comment]
See #182 which is based from #167. Other than that it also Provides some other fixes to the definition file and the resource script for the version info resource. The export Definition file was also fixed in it for all of the Project files and includes VS2013 for those who still use it. It targets the latest Develop branch though.

**Comment by madler** [comment]
Please see zlib 1.2.9 for updated vstudio support. Please create new issues or new pull requests if there are problems or desired behaviors against that version. Thanks.

**Pull request closed without merging**
