### PR TITLE
Corrected location of Visual Studio project files

### PR DESCRIPTION
**Pull request by JoeArizona**
There is no projects directory as referenced here. The VC project files are in contrib/vstudio. Relatedly, I suggest merging this two-line text file into the Win32 Readme, preferably on top somewhere.

### CODE REVIEW

**Comment by madler** [comment]
There are many Visual Studio pull requests. Can someone who is able to test them across versions of Visual Studio merge them into a single pull request? Also please test it with the latest zlib develop branch here on github, and account for functions that have been added since 1.2.8. Thank you.

**Comment by AraHaan** [comment]
See #182 which is based from #167. Other than that it also Provides some other fixes to the definition file and the resource script for the version info resource. The export Definition file was also fixed in it for all of the Project files and includes VS2013 for those who still use it. It targets the latest Develop branch though.

**Comment by madler** [comment]
Please see zlib 1.2.9 for updated vstudio support. Please create new issues or new pull requests if there are problems or desired behaviors against that version. Thanks.

**Comment by JoeArizona** [comment]
This was a fix to a document error. There is no `projects/` directory in the repo, but this doc refers people to such. That directory was removed in 1.2.4.2 back in 2010.

The actual location of the Visual Studio project files is `contrib/vstudio/...` That hasn't changed with the 1.2.9 updates. This was just about that error in the doc.

GitHub won't let me submit a pull request on the tag 1.2.9 – it says I need to be in a branch, and I guess the tags are not branches.

**Comment by JoeArizona** [comment]
Ah, good, thanks. I missed that part for some reason. Was there a 1.2.8.1 release? I don't see it anywhere.

**Comment by AraHaan** [comment]
Yes, there was but then a few days later bumped to v1.2.10. Also I think Mark sorta missed that updated text file too so don't worry @madler.

**Comment by madler** [comment]
Fixed that.

**Comment by madler** [comment]
No, there was not a 1.2.8.1 release. The github develop branch was numbered 1.2.8.1 until it became 1.2.9, and was then 1.2.9.1 until it became 1.2.10. However there was no release or tag with those version numbers.

**Pull request closed without merging**
