### PR TITLE
minizip: Correct filetime prototype on WIN32

### PR DESCRIPTION
**Pull request by xiaoxiang781216**

### CODE REVIEW

**Review by tbeu — APPROVED** [review]

**Comment by Neustradamus** [comment]
@gvollant: What do you think?

**Comment by gvollant** [comment]
I agree

**Comment by gvollant** [comment]
@madler you can merge it for me

**Comment by madler** [comment]
Applied.

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/f679a939d3db557fec0304602a179f0ac78e5afa

**Pull request closed without merging**
