### PR TITLE
add export statement for cmake config

### PR DESCRIPTION
**Pull request by ksophocleous**
allows dependent project to use `find_package(zlib CONFIG)`

namespace chosen to be `zlib::`

so the targets will look like this:
- `zlib::zlibstatic`
- `zlib::zlib`

### CODE REVIEW

**Comment by rcdailey** [comment]
Please see my PR (#295). I add a config package that is a bit more flushed out. Let me know if that one is useful to you.

**Comment by ksophocleous** [comment]
@rcdailey not sure your PR will be accepted due to the removal of `zconf.h`. I'll keep this one open until your PR is accepted. If yours is merged first, this one is irrelevant and will be closed.

Please make the namespace change `zlib::`, it would be quite nice to have that.

**Comment by rcdailey** [comment]
I am trying to get an explanation as to why `zconf.h` must be in version control. He mentioned "it's explained elsewhere" but did not mention *exactly* where. If you know, it would be great if you could point me in the right direction so I can understand it.

Also there's a functional reason to use the namespace, I removed it unintentionally but need to add it back. I will be amending my PR with that change plus others once I get more feedback about `zconf.h`.

Thanks and please do keep an eye out for those changes!

**Comment by timofonic** [comment]
@ksophocleous @rcdailey What about merging it to @Dead2 [zlib-ng](/Dead2/zlib-ng)?

**Comment by rickertm** [comment]
Pull request #148 also adds target export with version information and matching config file.

**Comment by ksophocleous** [comment]
I suppose this is outdated by now, I'll close this one

**Pull request closed without merging**
