### PR TITLE
minizip support for Haiku #741

### PR DESCRIPTION
**Pull request by gvollant**
Add support for Haiku #741

### CODE REVIEW

**Comment by gvollant** [comment]
@madler no risk to merge

**Comment by madler** [comment]
Thanks Gilles for looking at all those! @gvollant

**Comment by Begasus** [comment]
Thanks! 👍

**Comment by Neustradamus** [comment]
Zlib PR 830 from @gvollant Minizip author:
- https://github.com/madler/zlib/pull/830

"Support Haiku in minizip." merged commit in upstream Zlib develop branch:
- https://github.com/madler/zlib/commit/aa154e3da0d98629bbefe79cdfba8bc7178dc4ad

There is a little change.

Original HaikuPorts PR from Zoltán Mizsei @extrowerk (merged by @diversys) on GitHub:
- https://github.com/haikuports/haikuports/pull/1593

Zlib and Minizip HaikuPorts files:
- https://github.com/haikuports/haikuports/commits/master/app-arch/minizip
- https://github.com/haikuports/haikuports/commits/master/sys-libs/zlib/patches

Updated HaikuPorts PR from @Begasus:
- https://github.com/haikuports/haikuports/pull/7394

Requested PR in Zlib upstream from @Begasus:
- https://github.com/madler/zlib/pull/741

cc: @madler, @waddlesplash, @korli, @pulkomandy, @fbrosson.

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/aa154e3da0d98629bbefe79cdfba8bc7178dc4ad

**Pull request closed without merging**
