### PR TITLE
Fix C++ warning 4996

### PR DESCRIPTION
**Pull request by yaqiyang**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@yaqiyang: Why have you closed?

**Comment by madler** [comment]
Just as well. These changes have nothing to do with C++, but rather with MSVC, and the changes are incompatible with other platforms. Furthermore, the warnings are addressed with the `#define _CRT_SECURE_NO_WARNINGS` in gzguts.h. Lastly, no description was provided for this pull request.

Do you even look at the pull requests you comment on @Neustradamus ?

**Comment by Neustradamus** [comment]
@madler: I have been surprised that @yaqiyang has closed 2 minutes after ^^

**Comment by yaqiyang** [comment]
This has been a while, and I don't remember exactly why I closed it. I think I decided to use my own fork instead.

**Pull request closed without merging**
