### PR TITLE
Fix typos found by codespell in dotzlib

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
@hravnx Would you agree to fixing these typos in `zlib/contrib/dotzlib`?

**Review by hravnx — APPROVED** [review]

**Comment by spaette** [comment]
On Feb 17, 2023,  @hravnx approved the initial patch.

Unless othewise noted I'd presume he has no objections to these fixes added on Feb 18, 2023.

```
sed -i "s/dereived/derived/g" zlib/contrib/dotzlib/DotZLib/CodecBase.cs
sed -i "s/esclude/exclude/g" zlib/contrib/dotzlib/readme.txt
sed -i "s/proccesing/processing/g" zlib/contrib/dotzlib/DotZLib/CodecBase.cs
```

**Comment by madler** [comment]
Applied.

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/c7ddcc2e0e8bb397ad720564228b538135ec11d8

**Pull request closed without merging**
