### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by fluesvamp**

### CODE REVIEW

**Comment by fluesvamp** [comment]
@madler 

Any interest on your end in ChangeLog typo fixes?

**Comment by Neustradamus** [comment]
@madler, @gvollant: Can you look?

**Comment by fluesvamp** [comment]
I have already pinged Mark.

Please don't bother the Maintainers.

**Comment by fluesvamp** [comment]
Adler/Gailly

contrib/dotzlib/DotZLib/GZipStream.cs

concluded writeable was not a typo

<hr>

if the ChangeLog and/or contrib/minizip/MiniZip64_Changes.txt are to be modified uncomment the relevant lines

```
$ date
Sat Aug 20 13:20:03 CDT 2022
$ git clone -q https://github.com/madler/zlib.git
$ cat typos.sh
#!/bin/sh

# sed -i "s/Enchance/Enhance/g" zlib/ChangeLog
# sed -i "s/Suport/Support/g" zlib/ChangeLog
# sed -i "s/assmebler/assembler/g" zlib/ChangeLog
# sed -i "s/derrived/derived/g" zlib/contrib/minizip/MiniZip64_Changes.txt
# sed -i "s/indeterminancy/indeterminacy/g" zlib/ChangeLog
# sed -i "s/simplied/simplified/g" zlib/ChangeLog
sed -i "s/Asumes/Assumes/g" zlib/zlib2ansi
sed -i "s/Attension/Attention/g" zlib/contrib/ada/readme.txt
sed -i "s/Comression/Compression/g" zlib/contrib/ada/zlib-streams.ads
sed -i "s/Genererate/Generate/g" zlib/trees.c
sed -i "s/Similary/Similarly/g" zlib/zlib.h
sed -i "s/Simplfy/Simplify/g" zlib/examples/gzappend.c
sed -i "s/calcuated/calculated/g" zlib/crc32.c
sed -i "s/choosen/chosen/g" zlib/contrib/minizip/ioapi.h
sed -i "s/coments/comments/g" zlib/zlib2ansi
sed -i "s/comparision/comparison/g" zlib/contrib/minizip/unzip.h
sed -i "s/compearing/comparing/g" zlib/contrib/ada/test.adb
sed -i "s/completly/completely/g" zlib/make_vms.com
sed -i "s/concantenated/concatenated/g" zlib/examples/gun.c
sed -i "s/currenty/currently/g" zlib/contrib/minizip/zip.c
sed -i "s/decompresed/decompressed/g" zlib/examples/fitblk.c
sed -i "s/decompressd/decompressed/g" zlib/contrib/puff/pufftest.c
sed -i "s/decompressed/recompression/g" zlib/examples/fitblk.c
sed -i "s/defaut/default/g" zlib/contrib/minizip/unzip.c
sed -i "s/defaut/default/g" zlib/contrib/minizip/unzip.h
sed -i "s/depedent/dependent/g" zlib/contrib/minizip/zip.c
sed -i "s/dereived/derived/g" zlib/contrib/dotzlib/DotZLib/CodecBase.cs
sed -i "s/distribtution/distribution/g" zlib/contrib/infback9/inftree9.h
sed -i "s/distribtution/distribution/g" zlib/inftrees.h
sed -i "s/easilty/easily/g" zlib/contrib/minizip/unzip.c
sed -i "s/entires/entries/g" zlib/examples/enough.c
sed -i "s/esclude/exclude/g" zlib/contrib/dotzlib/readme.txt
sed -i "s/exmples/examples/g" zlib/make_vms.com
sed -i "s/explicitely/explicitly/g" zlib/os400/README400
sed -i "s/extened/extended/g" zlib/contrib/minizip/zip.c
sed -i "s/follwed/followed/g" zlib/contrib/puff/puff.c
sed -i "s/implmeneted/implemented/g" zlib/contrib/dotzlib/DotZLib/ChecksumImpl.cs
sed -i "s/incompartible/incompatible/g" zlib/contrib/ada/readme.txt
sed -i "s/insertor/inserter/g" zlib/contrib/iostream3/zfstream.h
sed -i "s/interupted/interrupted/g" zlib/examples/gzlog.h
sed -i "s/nevetheless/nevertheless/g" zlib/zlib.h
sed -i "s/opportunites/opportunities/g" zlib/deflate.c
sed -i "s/ouput/output/g" zlib/zlib.h
sed -i "s/proccesing/processing/g" zlib/contrib/dotzlib/DotZLib/CodecBase.cs
sed -i "s/readabilty/readability/g" zlib/contrib/puff/README
sed -i "s/readabilty/readability/g" zlib/contrib/puff/puff.c
sed -i "s/recreting/recreating/g" zlib/contrib/minizip/zip.c
sed -i "s/referece/reference/g" zlib/examples/zran.c
sed -i "s/reseting/resetting/g" zlib/zlib.h
sed -i "s/somes/some/g" zlib/contrib/minizip/unzip.h
sed -i "s/specfied/specified/g" zlib/examples/fitblk.c
sed -i "s/spetsified/specified/g" zlib/contrib/ada/test.adb
sed -i "s/stategy/strategy/g" zlib/contrib/ada/zlib.ads
sed -i "s/structore/structure/g" zlib/contrib/minizip/unzip.c
sed -i "s/structore/structure/g" zlib/contrib/minizip/zip.c
sed -i "s/suppors/supports/g" zlib/os400/README400
sed -i "s/suppported/supported/g" zlib/contrib/dotzlib/DotZLib/GZipStream.cs
sed -i "s/unusued/unused/g" zlib/examples/gzappend.c
$ cat typos.pl
#!/usr/bin/env perl

use strict;
use warnings;
use autodie;

my $fh;
my $file = 'typos';

open $fh, '<', $file;
while ( my $line = <$fh> ) {
    next if $line =~ /^\s*#/;
    my @typo = split '/', $line;
    my @path = split ' ', $line;
    print "grep -n $typo[1] $path[3]\n";
}

close $fh;
$ wc -l typos.sh
60 typos.sh
$ ed -s typos.sh <<<'3,60p' > typos
$ ./typos.pl > myfile
$ sh myfile
11:# Asumes no function pointer parameters. unless they are typedefed.
11:- Attension: ZLib.Read generic routine have a initialization requirement
65:   --  Create the Comression/Decompression stream.
315: * Genererate the file trees.h describing the static trees.
663:   Similary, if dictLength is Z_NULL, then it is not set.
918:   Similary, if dictLength is Z_NULL, then it is not set.
36: *                      - Simplfy and unify file operations
648:       instruction per cycle. Each CRC is calcuated on Z_BATCH words. The three
85:/* a type choosen by DEFINE */
107:  # Strip C & C++ coments
158:   If iCaseSenisivity = 1, comparision is case sensitivity (like strcmp)
159:   If iCaseSenisivity = 2, comparision is not case sensitivity (like strcmpi
73:   --  The procedure compearing data in 2 streams.
19:$! 0.07 20120115 Triggered by work done by Alexey Chupahin completly redesigned
46:   end-of-file, they cannot be concantenated.  If a Unix compress stream is
141:                                     currenty writing */
148:    int  method;                /* compression method of file currenty wr.*/
112:        /* compress what was decompresed until done or no room */
146:    /* if requested, inflate again and write decompressd data to stdout */
386:   If iCaseSenisivity = 0, case sensitivity is defaut of your operating system
161:   If iCaseSenisivity = 0, case sensitivity is defaut of your operating system
50:# define VERSIONMADEBY   (0x0) /* platform depedent */
142:        // performs the release of the handles and calls the dereived CleanUp()
41:   examples/enough.c found in the zlib distribtution.  The arguments to that
41:   examples/enough.c found in the zlib distribtution.  The arguments to that
850:   Translate date/time from Dos format to tm_unz (readable more easilty)
489:// shown. The maximum number of inflate table entires is then calculated across
39:   nunit={true|false} to include or esclude unit tests (default=true).
17:$! 0.06 20120111 Fix missing amiss_err, update zconf_h.in, fix new exmples
46:                text data code conversions must be done explicitely.
154:    int  zip64;               /* Add ZIP64 extened information in the extra field */
627: *   Each of 16, 17, and 18 are follwed by extra bits to define the length of
64:        /// <remarks>All the other <c>Update</c> methods are implmeneted in terms of this one.
12:  for Read_Last parameter now. It is a bit incompartible with previous version,
416:    // Allows insertor to peek at internals
43:   The gzlog operations can be interupted at any point due to an application or
1440:   multiple of size, then the final partial item is nevetheless read into buf
1683: * maximizes the opportunites to have a single copy from next_in to next_out.
279:  which can be used if desired to determine whether or not there is more ouput
163:        /// Copies a number of bytes to the internal codec buffer - ready for proccesing
41:are used to simplify error checking in the code to improve readabilty.  puff.c
46: *                        but leave simple version for readabilty
17:                                 It is used when recreting zip archive with RAW when deleting items from a zip.
24:   that block is saved to provide a referece for locating a desired starting
1445:   file, reseting and retrying on end-of-file, when size is not 1.
307:  if pfile_info!=NULL, the *pfile_info structure will contain somes info about
387:  return the number of byte copied if somes bytes are copied
20:   output size plus a specfied excess amount (see the EXCESS define
68:   --  Generate file of spetsified size with some random data.
117:   --  RLE stategy could be used only in version 1.2.0 and later.
156:    voidpf filestream;        /* io structore of the zipfile */
169:    voidpf filestream;        /* io structore of the zipfile */
168:    voidpf filestream;        /* io structore of the zipfile */
6:   If the installed IFS command suppors gzip format, this is straightforward,
249:        ///  Not suppported.
271:        /// Gets/sets the current position in the <c>GZipStream</c>. Not suppported.
288:        /// Gets the size of the stream. Not suppported.
57:   number of unusued bits in the last input byte used.  gzappend will not work
$ 
```

**Comment by madler** [comment]
I have incorporated most of these anyway. (Just not the ones in contrib that aren't mine.)

**Comment by Neustradamus** [comment]
@madler: I do not see merging of a part of this...

Note that contribs are not from you but it is important to update it...
zlib has "contrib", it is not good to do not update it.
If it is not updated, can you remove all here: https://github.com/madler/zlib/tree/master/contrib?

Can you use GitHub to merge it?
The problem is that all PR are not merged, and there is not a following...

**Comment by madler** [comment]
I haven't pushed it yet.

**Comment by madler** [comment]
I don't quite understanding what you're saying. Anyway, in general, I will leave it to the contributors to to update their own contributions.

**Comment by fluesvamp** [comment]
even if somewhat verbose posting my shell output made sense

among other reasons the pull request was opened as some software bundle zlib

**Comment by Neustradamus** [comment]
@madler: The problem is if contributors are not active, there are a lot badly.
And it is really easy to update it.

I can create a PR with contrib typo fixes from @fluesvamp but you will not merge it because I am not the original author of the contrib.
The solution is to remove contrib folder, it permits a better size if there is no change from the current situation.
- https://github.com/madler/zlib/tree/master/contrib

Normally master branch is up-to-date, and the important is the tag with build version and it will be better to develop...
- https://github.com/madler/zlib/tags

You can look other projects, for example PPP: https://github.com/ppp-project/ppp
PRs are merged (before with talk and changes if needed), commits are from the contributors and not from the original author (which always manages the project and do a good job):
- https://github.com/ppp-project/ppp/commits/master

You can compare with zlib:
- https://github.com/madler/zlib/commits/master

It is time to look all current PRs?
- https://github.com/madler/zlib/pulls

**Comment by fluesvamp** [comment]
everything concerning this pull request has been resolved

sometimes it is considered improper etiquette to continue posting after closing

closing was my decision and content was left for Maintainers' and/or contrib authors' review

**Comment by fluesvamp** [comment]
Adler/Gailly

contrib/README.contrib

```diff
- All files under this contrib directory are UNSUPPORTED. There were
+ All files under this contrib directory are UNSUPPORTED. They were
```

**Comment by madler** [comment]
Thanks. Fixed.

**Comment by Neustradamus** [comment]
Merged commits:
- https://github.com/madler/zlib/commit/5752b171fd4cc96b8d1f9526ec1940199c6e9740
- https://github.com/madler/zlib/commit/59b948acee57b77f9b018ac30ec2e4b499de5efd

**Pull request closed without merging**
