### PR TITLE
configure: just warn on unknown --with/without/enable/disable option

### PR DESCRIPTION
**Pull request by landfillbaby**
this seems to be the standard way, and makes it easier for me personally

### CODE REVIEW

**Comment by madler** [comment]
I'm missing why this is a good idea.

**Comment by landfillbaby** [comment]
Autoconf, for example, only warns by default. https://www.gnu.org/software/autoconf/manual/html_node/Option-Checking.html
> However, by default unknown --with-package and --enable-feature options elicit only a warning, to support configuring entire source trees.

**Comment by landfillbaby** [comment]
... Just realised I misread that. Maybe I should change this PR to allow only unknown `--with(out)-*` and `--(en|dis)able-*`.

**Comment by landfillbaby** [comment]
just realised i did this to masterinstead of develop

**Comment by Neustradamus** [comment]
@landfillbaby: Have you progressed on it?

You can use "develop" directly.

**Comment by landfillbaby** [comment]
closing in favour of #912

**Pull request closed without merging**
